PRO-1351 ubuntu cookbook
apostrophecms/a3-docs pull request #122
Opened 2021-07-26 16:54 UTC by abea

Migrates the Ubuntu guide to a recipe page and polishes for public consumption.

2021-07-26 16:55 UTC, abea commented on docs/cookbook/ubuntu-setup.md
> +# Ubuntu hosting setup
Unfortunately a few steps in git forgot this was changing the original guide page.

2021-07-26 17:08 UTC, boutell commented on docs/.vuepress/sidebar.js
> +        [ 'cookbook/ubuntu-setup.md', 'Ubuntu hosting setup 🆕' ]
This should be `ubuntu-hosting-setup` since we probably have separate guidance (or we will) on ubuntu as a dev environment.

2021-07-26 17:10 UTC, boutell requested changes
I think the slug of the page should still have "hosting" in it for avoidance of confusion with ubuntu dev environment guidance.

2021-07-27 20:46 UTC, boutell approved these changes

2021-07-27 21:01 UTC, merged