PRO-1814 Adds tip for using onReadyAndRefresh
apostrophecms/a3-docs pull request #128
Opened 2021-08-26 20:46 UTC by abea

2021-09-03 14:51 UTC, abea commented on docs/guide/front-end-tips.md
> +**What section are we talking about?** If you inspect an Apostrophe page's markup you will see a `div` tag with the `data-apos-refreshable` data attribute. That's the short answer. Anything inside th
I'm not sure I understand what you're suggesting. I'm putting it a callout note, which does seem better, but let me know if that's not what you had in mind.

2021-09-08 14:52 UTC, stuartromanek commented on docs/guide/front-end-tips.md
> +**What section are we talking about?** If you inspect an Apostrophe page's markup you will see a `div` tag with the `data-apos-refreshable` data attribute. That's the short answer. Anything inside th
I don't have the same confusion now that the section begins at a higher level 👍

2021-09-08 14:53 UTC, stuartromanek requested changes

2021-09-08 15:21 UTC, stuartromanek approved these changes

2021-09-08 20:02 UTC, merged