PRO-1810 Adds note on periods in module names
apostrophecms/a3-docs pull request #133
Opened 2021-09-07 18:54 UTC by abea

2021-09-08 11:14 UTC, boutell requested changes

2021-09-08 11:14 UTC, boutell commented on docs/guide/modules.md
> +Modules names may not include periods (`.`).
Module names, not modules names

2021-09-08 11:14 UTC, boutell commented on docs/guide/modules.md
> +Modules names may not include periods (`.`).
Otherwise good.

2021-09-08 19:54 UTC, agilbert approved these changes

2021-09-09 17:28 UTC, boutell approved these changes

2021-09-09 19:27 UTC, merged