Pro 2418 util
apostrophecms/a3-docs pull request #174
Opened 2022-01-13 21:39 UTC by abea

## Summary

PRO-2418

## What are the specific steps to test this change?

Review the documentation for accuracy and clarity

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [x] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [x] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-01-18 20:01 UTC, boutell requested changes

2022-01-18 21:59 UTC, abea commented on docs/reference/modules/_template.md
> +Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Sed posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
This is a template file providing structure for other module reference pages, hence the placeholder text.

2022-01-19 22:25 UTC, abea commented on docs/reference/modules/util.md
> +- **`source`**: A string that will be mutated by replacing substrings.
This is true. I was trying to get at how this doesn't return the updated version, but my wording is bad.

2022-01-19 22:35 UTC, abea commented on docs/reference/modules/util.md
> +`path` supports dot notation like MongoDB. If the first dot notation segment of `path` begins with `@xyz` (or `@` followed by any alphanumeric value) the nested object within `obj` with an `_id` prop
I'm trying to get at what the method returns. I actually got that phrasing from your original code comment. I don't think I understand what your replacement text is getting at.

2022-01-19 22:52 UTC, abea commented on docs/reference/modules/util.md
> +If the `list` argument is a string, returns `true` if it starts with the value `val`. If the `list` argument is an array, returns true if *at least one* of its items begins with `val`.
Yeah. We don't have to document it and can mark it for deprecation.

2022-01-20 21:43 UTC, boutell approved these changes

2022-01-20 21:45 UTC, merged