add missing snippets
apostrophecms/a3-docs pull request #352
Opened 2023-08-04 09:42 UTC by haroun

## Summary

Add missing snippets to the documentation to improve DX.

When trying the user settings for the first time, it was not clear to me what the actual steps were to achieve the UI language switcher.

This will require some additional work and rephrasing, maybe a screenshot

## What are the specific steps to test this change?

1. Check `doc/reference/modules/settings.md` preview

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [x] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-08-04 12:49 UTC, BoDonkey commented on docs/reference/modules/settings.md
> +All fields must be part of the `@apostrophecms/user` schema, except `adminLocale` that will be added automatically to
```suggestion
All fields added to the subforms must be included as default fields or added to the `@apostrophecms/user` schema, except `adminLocale`. 
```

2023-08-04 12:55 UTC, BoDonkey commented on docs/reference/modules/settings.md
> +`@apostrophecms/user` if the `adminLocales` option is set in the `@apostrophecms/i18n` module.
```suggestion
If the `adminLocales` option is set in the `@apostrophecms/i18n` module, this field will be automatically added to the available subform schema fields and will add a select input for Admin language to the User management modal.
```

2023-08-04 12:56 UTC, BoDonkey commented on docs/reference/modules/settings.md
> +<template v-slot:caption>
Doh!

2023-08-04 12:57 UTC, boutell requested changes

2023-08-04 13:02 UTC, BoDonkey commented on docs/reference/modules/settings.md
> +<AposCodeBlock>
We could consider making this shorter, in case the user wants to copy-paste there is less to toss if it doesn't pertain to their project.

2023-08-04 13:04 UTC, BoDonkey requested changes
Both Tom and I made suggestions, but feel free to edit specific word usage.

2023-08-04 13:04 UTC, BoDonkey commented on docs/reference/modules/settings.md
> +      // The `adminLocale` option must be configured in the `@apostrophecms/i18n` module for this to be allowed
Oops!

2023-08-04 14:46 UTC, haroun commented
I did not changed `displayName` to bind to `title` because there is some `previewComponent` logic in `SettingsDisplayNamePreview` I'm not familiar with yet that must be migrated too.

2023-08-04 14:47 UTC, haroun commented on docs/reference/modules/settings.md
> +      // The `adminLocale` option must be configured in the `@apostrophecms/i18n` module for this to be allowed
there was a typo also, it is `adminLocales` option

2023-08-04 16:03 UTC, boutell commented
I see your point. If we don't add `firstName` and `lastName` to `@apostrophecms/user` in this example, then there is no motivation for the custom previewer.

I suggest breaking it into two steps then: (1) here's a swell config for 99% of sites, no custom preview required. (2) here's a use case with firstName and lastName, thus a use for custom preview.

2023-08-04 20:44 UTC, boutell requested changes
I see your point. If we don't add firstName and lastName to @apostrophecms/user in this example, then there is no motivation for the custom previewer.

I suggest breaking it into two steps then: (1) here's a swell config for 99% of sites, no custom preview required. Almost everybody: you're done now!

(2) here's a use case with firstName and lastName, thus a use for custom preview.

2023-08-10 12:59 UTC, haroun commented
@BoDonkey I've reassigned you the PR to address the change Tom requested but with `displayName` instead

2023-08-15 14:26 UTC, boutell approved these changes
Looks good. I still wish we were starting with a config that works out of the box on every site and then separately talking about fields you might add at project level, but that concern can be better addressed in another way by enabling this module in our starter kits, so that people aren't likely to even get here unless they want to tweak it.

2023-08-15 14:30 UTC, merged