add uponSubmit requirements documentation
apostrophecms/a3-docs pull request #360
Opened 2023-11-10 09:01 UTC by haroun

## Summary

Add `uponSubmit` phase to Login requirements

## What are the specific steps to test this change?

Check the `custom-login-requirements` doc

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [x] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-11-10 16:40 UTC, boutell requested changes

2023-11-10 16:40 UTC, boutell commented on docs/guide/custom-login-requirements.md
> +* `uponSubmit`: Requirements in this phase are displayed after the user clicks the Login button, but before any password verification takes place. Best used for requirements that must re-run each tim
click on -> clicks on

Also include the "best used for requirements that have no visible interface..." text because that's true here too

2023-11-10 16:40 UTC, boutell commented on docs/guide/custom-login-requirements.md
> +* `uponSubmit` requirements may emit a `block` event to cancel a previous `done` event so that the Login can be clicked again.
Login -> Login button

2023-11-10 16:40 UTC, boutell commented on docs/guide/custom-login-requirements.md
> +* `uponSubmit` requirements may emit a `block` event to cancel a previous `done` event so that the Login can be clicked again.
Line 97 isn't quite right. "any UI for `beforeSubmit` will appear simultaneously with the login form. Any UI for `uponSubmit` will appear after the Login button is clicked and remain until each has emitted a `done` event.

2023-12-12 16:36 UTC, haroun commented
Moved to https://github.com/apostrophecms/a3-vitepress-docs/pull/78

2023-12-12 16:36 UTC, closed without merging