PRO-940 Introduction
apostrophecms/a3-docs pull request #51
Opened 2021-03-23 22:05 UTC by abea

2021-03-24 21:15 UTC, abea commented
... Should this section also talk about what widgets and whatnot are?

2021-03-24 21:43 UTC, localghost443 requested changes
Really really good. Two small adjustment requests.

2021-03-24 21:43 UTC, localghost443 commented on docs/guide/introduction.md
> +- a great UI for creating content, including in-context editing with content widgets
```suggestion
- a great UI for creating content, including in-context editing
```

2021-03-24 21:43 UTC, localghost443 commented on docs/guide/introduction.md
> +In short, it recognizes pain points on both sides of the CMS experience and relieves them. We can start getting to know that system with two foundational concepts: modules and content schemas.
```suggestion
In short, it recognizes pain points on both sides of the CMS experience and relieves them. We can start getting to know that system with two foundational concepts: modules and content schemas.
```
```suggestion
In short, it recognizes pain points on both sides of the CMS experience and relieves them. Apostrophe is built on two foundational concepts: modules and content schemas.
```

2021-03-25 19:11 UTC, abea commented on docs/guide/introduction.md
> +In short, it recognizes pain points on both sides of the CMS experience and relieves them. We can start getting to know that system with two foundational concepts: modules and content schemas.
I'll simply delete this sentence.

2021-03-25 19:22 UTC, localghost443 approved these changes

2021-03-25 19:23 UTC, merged