PRO-1152 relationships
apostrophecms/a3-docs pull request #67
Opened 2021-04-16 17:00 UTC by abea

2021-04-16 17:15 UTC, abea commented
relationshipReverse fields don't seem to be working at the moment, so I'm commenting out that section until it can be confirmed. https://linear.app/apostrophecms/issue/PRO-90/relationshipreverse-fields-may-not-work-yet

2021-04-19 19:45 UTC, localghost443 requested changes

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +For the purposes of this guide, we will focus on the piece type code. If following along, refer to the [pieces guide](/guide/pieces.md) for more information on adding piece types, including instantia
```suggestion
Refer to the [pieces guide](/guide/pieces.md) for more information on adding piece types.
```

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +## Connecting related docs in the interface
```suggestion
## Creating relationships in the interface
```

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +When someone creates or edits an article, the editor will now include a relationship field. They can type in the name of a topic or use the "Browse" button to view the full list of topics to choose.
```suggestion
Once a relationship field is added to the schema, the editor will now include a relationship field. They can type in the name of a topic or use the "Browse" button to view the full list of topics to choose.
```
Something like this.

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +## Limiting the number of connected docs
```suggestion
## Limiting the number of relationships
```

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +Sometimes a doc should only connect to one other doc through a relationship field. Other times you may want to require a minimum number of relationships. Both can be achieved using the `min` and `max
Sometimes only one relationship is required, but sometimes, you want many.

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +## Reading the relationship from the "reverse" side
```suggestion
## Reverse relationships
```

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +Relationships are directional, but you can still read the relationship from the opposite direction using a `reverseRelationship` field. A `reverseRelationship` field must be reflecting an existing `r
```suggestion
Relationships are directional, but you can still read the relationship from the opposite direction using a `reverseRelationship` field. A `reverseRelationship` field must reflect an existing `relationship` field. **It has no user interface or property in database documents.** It is simply a signal for Apostrophe to populate data when fetching a document.
```

2021-04-19 19:45 UTC, localghost443 commented on docs/guide/relationships.md
> +You don't need to use a fields `group` setting here since the `relationshipReverse` field has no user interface.
Note?

2021-04-20 14:53 UTC, localghost443 approved these changes

2021-04-20 14:59 UTC, merged